name: json_ast
version: 1.0.5
author: Javier Lecuona <javierlecuona@gmail.com>
description: A library that builds the abstract syntax tree for a JSON string.
homepage: https://github.com/javiercbk/json_ast
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:

dev_dependencies:
  test: ^1.16.8
  path: ^1.8.0
